
server:
  port: 8012

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: MANUAL
    virtual-host: my_vhost
  application:
    name: test-mq
